### ISSUE TITLE
prusa is changing the M73 gcode

### ISSUE THREAD

**Issue by adcurtin** [NilsRo/OctoPrint-SlicerEstimator#14]
just a heads up more than anything else. prusa is changing the M73 Gcode slightly in a future firmware release.

```
G-code M73 has been extended with two parameters: C (for normal mode) and D (for stealth mode). Until now, the PrusaSlicer produced pairs of lines in the form of (example):
M73 P15 R30

Once this feature is fully implemented, the code will look as follows:
M73 P15 R30 C15
```

from here: https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.10.0-RC1

**Comment by NilsRo** [comment]
Thanks a lot. I implement a change to support old and new format. It published with Release 1.0.1
