### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by GydeonMylls** [NilsRo/OctoPrint-SlicerEstimator#16]
The version 1.0.1 release still reports to be version 1.0.0 in the [setup file](https://github.com/NilsRo/OctoPrint-SlicerEstimator/blob/master/setup.py#L17), causing Octoprint to endlessly prompt to update.

**Comment by NilsRo** [comment]
Thanks a lot. Forgot to change the version number, this happens when doing changes in the coffee break :-)
