### ISSUE TITLE
Add execution of G-Code commands upon remaining time

### ISSUE THREAD

**Issue by Cheap-Tricks** [NilsRo/OctoPrint-SlicerEstimator#2]
I like to turn off my glass bed heater ~6 minutes before the end of the print to make pulling the part off easier. Could you add a feature such that when time remaining is more or less than some specified value a command is executed?

**Comment by NilsRo** [comment]
This could be normally achieved in the slicer. I know from Cura that you can do that in the Post Processing which should be a good place for it. 

For this a separate plugin should be created as it is not linked to print time estimation.
