### ISSUE TITLE
Just getting green dot, no checkmark.

### ISSUE THREAD

**Issue by chrishilbert** [NilsRo/OctoPrint-SlicerEstimator#20]
Running PrusaSlicer 2.3.0 with a Prusa mini on OctoPrint 1.5.3.  Plugin updated today to current version.  Only seeing green dot, no checkmark.

I have 2 Minis, Pis running the same setup.  Neither work with this plugin running.  Suspect it's in conflict with some other plugin.

![Screen Shot 2021-03-29 at 1 32 54 PM](https://user-images.githubusercontent.com/2332975/112876266-4ceb1880-9093-11eb-838d-62615d42b4df.png)

**Comment by NilsRo** [comment]
Hi Chris.

A green dot is a very good average estimation. If you enabled this checkbox it will be used instead if available. 
![grafik](https://user-images.githubusercontent.com/51311453/112887962-108bdc80-90d4-11eb-9464-2dbf1cc38f82.png)

But perhaps there is something wrong with the exchange of the checkmark as there was a Syntax error I had to correct at exactly this point. Can you enable debug log and attach the octoprint.log file. I can check the behaviour of the plugin then. Also a list of installed plugins would be nice to check if there could be some conflicting. I printed 3 jobs with the actual version but sliced with Cura without issues. If you like to simulate a print simply enable "virtual printer", should be the last entry in the plugins and connect to port VIRTUAL. So you have not to waste material.

![grafik](https://user-images.githubusercontent.com/51311453/112888275-711b1980-90d4-11eb-8109-3d6be7fd30a3.png)

**Comment by chrishilbert** [comment]
I do have that box checked.  Do you still need the logs if it's operating as expected then?

**Comment by NilsRo** [comment]
No, everything is like expected then. 

You can find details on the Github Homepage. The average estimation is not a real estimation it is an average of the last real prints if you printed an object more than once. It does also include heatup time so it will be different from slicer estimation. The slicer does not know how long the printer will heat up...so you can set it like your need...with heatup and based on history or slicer estimation everytime.   If you preheat the printer "sometimes" the average estimation could be slightly off.
