### ISSUE TITLE
Cura is not detected

### ISSUE THREAD

**Issue by jjvelar** [NilsRo/OctoPrint-SlicerEstimator#39]
## Description
Hi
Cura is not automatically detected.
Please advise.
Best regards,

José

**Plugins installed**
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- Auto Terminal Input[AutoTerminalInput] v0.1.0
- Autoscroll[autoscroll] v0.0.3
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- Calibration Tools[CalibrationTools] v1.0.4
- Cancel Objects[cancelobject] v0.4.7
- Custom Control Editor[customControl] v0.2.2
- Dashboard[dashboard] v1.19.8
- Detector2 Plugin[detector2] v0.1.4
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- DisplayZ[displayz] v0.2.0
- Draggable Files[draggable_files] v1.0.4
- Dragon Order[dragon_order] v0.1.7
- Emergency Stop Simplified[emergencystopsimplified] v0.1.1
- Enclosure Plugin[enclosure] v4.13.2
- Filament Sensor Simplified[filamentsensorsimplified] v0.3.3
- Fullscreen Plugin[fullscreen] v0.0.6
- GcodeEditor[GcodeEditor] v0.2.12
- InlineConfirm[inlineconfirm] v1.1.4
- ipOnConnect[ipOnConnect] v0.2.4
- Long-SD-list-paths[LongPathSDList] v1.1.0
- Macro[macro] v0.3.2
- Marlin EEPROM Editor[eeprom_marlin] v3.2.0
- Marlin GCode Documentation[marlingcodedocumentation] v0.18.0
- Multi Line Terminal[multilineterminal] v0.1.5
- Navbar Temperature Plugin[navbartemp] v0.15
- OctoPod Plugin[octopod] v0.3.14
- Plotly Temp Graph[plotlytempgraph] v0.1.3
- PortLister[portlister] v0.1.10
- PrinterAlerts[PrinterAlerts] v0.7.5
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- ProgressBasedOntime Plugin[ProgressBasedOnTime] v0.1.6
- RequestSpinner[requestspinner] v0.2.0
- Resource Monitor[resource_monitor] v0.3.6
- Simple Emergency Stop[simpleemergencystop] v1.0.5
- Slicer Estimator[SlicerEstimator] v1.5.2
- Stateful Sidebar[statefulsidebar] v0.1.2
- Tab Order[taborder] v0.5.12
- Tempsgraph Plugin[tempsgraph] v0.3.7
- Terminal Messaging[terminalmessaging] v0.1.0
- Timelapse Purger[timelapsepurger] v0.1.3
- TP-Link Smartplug[tplinksmartplug] v1.0.2
- WLED Connection[wled] v0.2.1
- Z Probe Offset[z_probe_offset] v0.5

**Settings**
- average_prio: true
- metadata_filelist: true
- metadata_filelist_align: top
- metadata_list: 
- metadata_printer: true
- pdp: 1
- php: 1
Installed plugins: (SlicerEstimator)
- pmp: 2
- psp: 3
- pwp: 1
- useDevChannel: false
- use_assets: true

**Software versions**
- OctoPrint 1.8.2
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by NilsRo** [comment]
Nice tinder that so many people using the plugin. 😀 Please update to 1.5.3 using the force update method or ignore the notification until OctoPrint informs you about a new version. 

It was a mistake from me, forgot to delete a debugging setting so it throws this warning every time. But it's the warning only that's going wrong.
