### ISSUE TITLE
Slicer Estimator Error

### ISSUE THREAD

**Issue by Plumpkatt1** [NilsRo/OctoPrint-SlicerEstimator#42]
## Description
**Slicer Estimator Error
Describe your problem? When I upload a Gcode file Octoprint says o open a ticket for Slicer Estimator Plugin
What is the problem?
Can you recreate it? every time
Did you try disabling plugins? no
Did you remember to update the subject?** yup

**Plugins installed**
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- BLTouch Plugin[BLTouch] v0.3.4
- ExtraFileInfo[extrafileinfo] v1.3.0
- Slicer Estimator[SlicerEstimator] v1.5.3
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.0
- SlicerSettingsParser[SlicerSettingsParser] v2.0.1

**Settings**
- average_prio: true
- metadata_filelist: true
- metadata_filelist_align: top
- metadata_list: 
- metadata_printer: true
Installed plugins: (SlicerEstimator)
- useDevChannel: false
- use_assets: true

**Software versions**
- OctoPrint 1.8.2
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36

**Comment by NilsRo** [comment]
Hi. 

What slicer are you using?
