### ISSUE TITLE
No configuration GUI shown...

### ISSUE THREAD

**Issue by energiebrand** [NilsRo/OctoPrint-SlicerEstimator#5]
I have installed the PlugIn but there is no configuration GUI shown.
See the attached Releases and picture of the GUI. 

I did remove the installation and then re-installed but with the same result.

![Nothing to see](https://user-images.githubusercontent.com/60507600/109658885-6322b900-7b67-11eb-9192-205e47d6c0b0.jpg)

![Releases](https://user-images.githubusercontent.com/60507600/109658890-63bb4f80-7b67-11eb-9721-27856972b4f1.jpg)

**Comment by NilsRo** [comment]
This was a bug 4 hours online for new installations. The defaults settings was wrong (and during my tests I did not do a clean install to my regret). It is fixed and released in 0.51 since 37 minutes.

**Comment by energiebrand** [comment]
Ok, thanks a lot for fast feedback! Will test a new installation tomorrow, just started printing :-)

**Comment by energiebrand** [comment]
Ok, working now! Thanks a lot!
