### ISSUE TITLE
Parsing colors from *.mfc.gcode files

### ISSUE THREAD

**Issue by dirkvranckaert** [NilsRo/OctoPrint-SlicerEstimator#62]
I was looking to this plugin because it can read metadata, so I was wondering if the parsing can be a bit more dynamic.

I'm using Mosaic Palette 2 with the P2PP configured from PrusaSlicer and that exports me a `mfc.gcode` file containing following line (in this case a 3 color print):
`O25 D10A0504BlackPLA D1FFFFFFWhitePLA D16CBC66DarkKhakiPLA D0`

So I was wondering if I can't parse this with your plugin to show me a list (comma separated or so is good enough) of colors within this print. This way I could first prepare my spools before starting the entire multi color print chain.

**Comment by NilsRo** [comment]
Hi, can you upload the whole file. 

Perhaps you can add this information as a comment via placeholders? https://help.prusa3d.com/article/list-of-placeholders_205643  Personally I do not use PrusaSlicer so do not know what is possible...
