### ISSUE TITLE
Feature Request: Add support for Snapmaker Luban

### ISSUE THREAD

**Issue by firebadnofire** [NilsRo/OctoPrint-SlicerEstimator#78]
## Feature Request: Add support for Snapmaker Luban

I am requesting support for Snapmaker's [Luban](https://github.com/Snapmaker/Luban) slicer software as it is what I use and it currently lacks support

**Comment by NilsRo** [comment]
Hi. Could you upload an example GCode. Please activate remaining time calculation if possible, as it is sometimes necessary for some slicers (e.g. prusa).

**Comment by firebadnofire** [comment]
Here's an example gcode from Luban
[example.zip](https://github.com/user-attachments/files/16822975/example.zip)

**Comment by NilsRo** [comment]
Please activate the development branch in the settings tab of the plugin and run some tests. I added support there for Luban with time estimation and comment (metadata) extraction.

**Comment by firebadnofire** [comment]
It looks like it works 👍

**Comment by NilsRo** [comment]
Luban support is released...
